* Encoding: UTF-8.

T-TEST GROUPS= in‑hospital mortality (0 1)
  /MISSING=ANALYSIS
  /VARIABLES=Age BMI
  /ES DISPLAY(TRUE)
  /CRITERIA=CI(.95).
CROSSTABS
  /TABLES=Ethnicities Sex Smoker Hypertension Diabetes MACE Liver disease Renal disease Chronic pulmonary disease Malignant neoplasms Organ transplant HIV infection CMV infection Glucocorticoids Vasopressor Ventilation Kidney dialysis BY in‑hospital mortality
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT
  /COUNT ROUND CELL.

NPAR TESTS
  /M-W= LDH Creatinine WBC RBC Platelet Hemoglobin Albumin Lymphocyte count Neutrophil count Monocyte count NLR SAPSII score SOFA score OASIS score BY 
  in‑hospital mortality (0 1)
  /MISSING ANALYSIS.

ROC NLR BY ICU 28‑day mortality
  /PLOT=CURVE
  /CRITERIA=CUTOFF(INCLUDE) TESTPOS(LARGE) DISTRIBUTION(FREE) CI(95)
  /MISSING=EXCLUDE.



ROC ANALYSIS NLR LDH BY ICU 28‑day mortality
  /MISSING USERMISSING=EXCLUDE
  /CRITERIA CUTOFF=INCLUDE TESTPOS=LARGE CI=95
  /DESIGN PAIR=TRUE
  /PLOT CURVE=ROC MODELQUALITY=FALSE
  /PRINT SE=FALSE CLASSIFIER=FALSE.

ROC ANALYSIS NLR SOFA score BY ICU 28‑day mortality
  /MISSING USERMISSING=EXCLUDE
  /CRITERIA CUTOFF=INCLUDE TESTPOS=LARGE CI=95
  /DESIGN PAIR=TRUE
  /PLOT CURVE=ROC MODELQUALITY=FALSE
  /PRINT SE=FALSE CLASSIFIER=FALSE.

ROC ANALYSIS NLR OASIS score BY ICU 28‑day mortality
  /MISSING USERMISSING=EXCLUDE
  /CRITERIA CUTOFF=INCLUDE TESTPOS=LARGE CI=95
  /DESIGN PAIR=TRUE
  /PLOT CURVE=ROC MODELQUALITY=FALSE
  /PRINT SE=FALSE CLASSIFIER=FALSE.

